import scans from "../../public/data/art-manifest.json";
import raw from "../../public/data/core-2026.json";
import type { Card, Difficulty } from "./types";
import { SPREADING_FLAMES } from "./scenario";
export const cards = raw as Card[];
// Null-prototype maps: a code such as "__proto__" or "constructor" from an
// imported file must look up nothing, never an Object.prototype member.
export const cardMap: Record<string, Card> = Object.assign(
  Object.create(null),
  Object.fromEntries(cards.map((c) => [c.code, c])),
);
export const card = (code: string) => cardMap[code];
// Keep the scripted scenario's pool fixed. The collection is loaded on demand
// and registered only for read-only inspection, never for game setup or saves.
export function registerCatalogCards(imported: Card[]) {
  for (const c of imported) if (!cardMap[c.code]) cardMap[c.code] = c;
}
export const code = (n: number) => String(12000 + n);
export const investigators = cards.filter(
  (c) => c.type_code === "investigator",
);
export const JOE_DECK = [
  30, 31, 32, 33, 34, 35, 16, 17, 18, 19, 20, 21, 87, 87, 88, 88, 5, 36, 37, 38,
  22, 23, 24, 89, 89, 39, 25, 93, 93, 92, 92, 6, 100,
].map(code);
export const DANIELA_DECK = [
  2, 16, 17, 18, 19, 20, 21, 72, 73, 74, 75, 76, 77, 86, 86, 88, 88, 22, 23, 24,
  78, 79, 89, 89, 25, 80, 81, 92, 92, 94, 94, 3, 104,
].map(code);
export const TRISH_DECK = [
  8, 44, 45, 46, 47, 48, 49, 30, 31, 32, 33, 34, 35, 86, 86, 88, 88, 50, 51, 52,
  36, 37, 38, 89, 89, 53, 39, 91, 91, 93, 93, 9, 103,
].map(code);
// Rulebook pages 28–29: Dexter Drake and Isabelle Barnes starter decks.
export const DEXTER_DECK = [
  58, 59, 60, 61, 62, 63, 44, 45, 46, 47, 48, 49, 86, 86, 88, 88, 11, 64, 65,
  66, 50, 51, 52, 89, 89, 67, 53, 90, 90, 91, 91, 12, 101,
].map(code);
export const ISABELLE_DECK = [
  14, 72, 73, 74, 75, 76, 77, 58, 59, 60, 61, 62, 63, 86, 86, 88, 88, 78, 79,
  64, 65, 66, 89, 89, 80, 81, 67, 94, 94, 90, 90, 15, 102,
].map(code);
export const STARTER_DECKS: Record<string, string[]> = Object.assign(
  Object.create(null),
  {
    "12004": JOE_DECK,
    "12001": DANIELA_DECK,
    "12007": TRISH_DECK,
    "12010": DEXTER_DECK,
    "12013": ISABELLE_DECK,
  },
);
export const PLAYABLE_INVESTIGATORS = [
  "12004",
  "12001",
  "12007",
  "12010",
  "12013",
];
export const BAGS: Record<Difficulty, string[]> = {
  easy: [
    "+1",
    "+1",
    "0",
    "0",
    "0",
    "-1",
    "-1",
    "-1",
    "-2",
    "-2",
    "skull",
    "skull",
    "tablet",
    "elder_thing",
    "auto_fail",
    "elder_sign",
  ],
  standard: [
    "+1",
    "0",
    "0",
    "-1",
    "-1",
    "-1",
    "-2",
    "-2",
    "-3",
    "-4",
    "skull",
    "skull",
    "tablet",
    "elder_thing",
    "auto_fail",
    "elder_sign",
  ],
  hard: [
    "0",
    "0",
    "0",
    "-1",
    "-1",
    "-2",
    "-2",
    "-3",
    "-3",
    "-4",
    "-5",
    "skull",
    "skull",
    "tablet",
    "elder_thing",
    "auto_fail",
    "elder_sign",
  ],
  expert: [
    "0",
    "-1",
    "-1",
    "-2",
    "-2",
    "-3",
    "-3",
    "-4",
    "-4",
    "-5",
    "-6",
    "-8",
    "skull",
    "skull",
    "tablet",
    "elder_thing",
    "auto_fail",
    "elder_sign",
  ],
};
export const CONNECTIONS: Record<string, string[]> =
  SPREADING_FLAMES.connections;
export const MAP_POS: Record<string, [number, number]> = {
  "12113": [10, 50],
  "12117": [29, 50],
  "12116": [50, 50],
  "12118": [71, 18],
  "12119": [71, 82],
  "12120": [91, 50],
};
export const plain = (s = "") =>
  s
    .replace(/<[^>]*>/g, "")
    .replace(/\[\[([^\]]+)\]\]/g, "$1")
    .replace(/\[action\]/g, "→")
    .replace(/\[fast\]/g, "◇")
    .replace(/\[reaction\]/g, "↳")
    .replace(/\[per_investigator\]/g, "per investigator")
    .replace(/\[([^\]]+)\]/g, "$1");
export const CARD_ART: Record<string, string> = {
  ...scans,
  // Visually verified against both faces: the campus locations use `b` for
  // their revealed side, but Your Friend's Room uses the opposite convention.
  // Default inspection should show the same rules face as the current text.
  ...Object.fromEntries(
    ["12116", "12117", "12118", "12119", "12120"]
      .filter((code) => (scans as Record<string, string>)[`${code}b`])
      .map((code) => [code, (scans as Record<string, string>)[`${code}b`]]),
  ),
  "12004": "/art/joe-card.webp",
  "12005": "/art/intuition.webp",
  "12031": "/art/fingerprint.webp",
  "12034": "/art/magnifying.webp",
};
// Table, hand and archive views use the smaller face; inspection and
// magnification use the full face. Both are generated by scripts/optimize-art.mjs.
export const thumbArt = (src?: string) =>
  src && src.startsWith("/art/cards/")
    ? src.replace("/art/cards/", "/art/cards/thumb/")
    : src;
export const cardArt = (c: Card, reverse = false) => {
  const local = CARD_ART[reverse ? `${c.code}b` : c.code];
  if (local) return local;
  const src = reverse ? c.backimagesrc : c.imagesrc;
  return src?.startsWith("/") ? `https://arkhamdb.com${src}` : src;
};
/** Keep the existing local scans first. The published rules asset host offers
 * a second source for exact printing identifiers when ArkhamDB is unavailable.
 * An unavailable printing falls back to the readable card face.
 */
export const cardArtSources = (c: Card, reverse = false): string[] => {
  const primary = cardArt(c, reverse);
  const published = /^\d{5}[a-z]*$/.test(c.code)
    ? `https://assets.arkhamhorror.app/img/arkham/cards/${c.code}${reverse ? "b" : ""}.avif`
    : undefined;
  return [...new Set([primary, published].filter((v): v is string => !!v))];
};
export const CARD_BACKS = {
  player: "/art/backs/player.webp",
  encounter: "/art/backs/encounter.webp",
} as const;
// Do not infer a location's reveal state from ArkhamDB's filename suffix.
export const LOCATION_ART: Record<
  string,
  { revealed: string; unrevealed: string }
> = {
  "12113": { revealed: "12113", unrevealed: "12113b" },
  "12116": { revealed: "12116b", unrevealed: "12116" },
  "12117": { revealed: "12117b", unrevealed: "12117" },
  "12118": { revealed: "12118b", unrevealed: "12118" },
  "12119": { revealed: "12119b", unrevealed: "12119" },
  "12120": { revealed: "12120b", unrevealed: "12120" },
};
